development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] %>
  channel_prefix: SITEWORKR_production


development:
  adapter: redis
  url: 'redis://localhost:6379/1'
