meta_product_name: "Siteworkr"
meta_title: "Siteworkr - Find a Workr"
meta_description: "On demand recruitment solution connecting local skilled workers to construction companies"
meta_image: "siteworkr-logo.png"                       # should exist in `app/assets/images/`
twitter_account: "@siteworkr"
